# Generated by Django 3.2.12 on 2022-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mask2faceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('number', models.IntegerField(max_length=4)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
