# Generated by Django 3.2.12 on 2022-04-13 15:30

from django.db import migrations, models
import mask2face.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mask2faceDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('input', models.ImageField(upload_to=mask2face.models.input_directory_path)),
                ('output', models.ImageField(upload_to=mask2face.models.output_directory_path)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
