# Generated by Django 3.2.12 on 2022-03-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mask2face', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mask2facedb',
            name='number',
        ),
        migrations.AddField(
            model_name='mask2facedb',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
