# Generated by Django 3.2.12 on 2022-05-08 12:44

from django.db import migrations, models
import mask2face.models


class Migration(migrations.Migration):

    dependencies = [
        ('mask2face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mask2facedb',
            name='output',
            field=models.ImageField(blank=True, upload_to=mask2face.models.output_directory_path),
        ),
    ]
